### ISSUE TITLE
Container fails to listen on IP:PORT provided

### ISSUE THREAD

**Issue by manofcolombia** [linuxserver/docker-cardigann#14]
After launching container:

`
time="2019-04-21T17:41:43Z" level=info msg="Cardigann v1.10.2
time="2019-04-21T17:41:43Z" level=info msg="Reading config from /config/config.json" 
time="2019-04-21T17:41:43Z" level=info msg="Found 3 indexers enabled in configuration"
time="2019-04-21T17:41:43Z" level=info msg="Listening on 0.0.0.0:tcp://172.30.15.208:5060"
cardigann: error: listen tcp: address 0.0.0.0:tcp://172.30.15.208:5060: too many colons in address, try --help`

linuxserver/docker-jackett is working as expected and begins listening on the exposed port with no issues. Both have essentially the same configuration within OKD. 

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
	

OKD 3.11

**Comment by aptalca** [comment]
Please post your docker create or compose yml

**Comment by manofcolombia** [comment]
`  
name: cardigann-5-8zk84
  namespace: plex-monitoring
  ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: cardigann-5
      uid: b5f665ff-645c-11e9-bc6f-000c2927fc6e
  resourceVersion: '2152672'
  selfLink: /api/v1/namespaces/plex-monitoring/pods/cardigann-5-8zk84
  uid: b81307eb-645c-11e9-b4cf-000c29fd6ea8
spec:
  containers:
    - env:
        - name: PUID
          value: '99'
        - name: PGID
          value: '100'
      image: >-
        docker.io/linuxserver/cardigann@sha256:21c46b5941dc4c7f621285acd1e8882a8eb11365f50fe308aef150ee301ced72
      imagePullPolicy: Always
      name: cardigann
      ports:
        - containerPort: 5060
          protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
            - MKNOD
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /config
          name: cardigann
`

**Comment by aptalca** [comment]
You didn't provide the info we asked for. Closing for now. You can reopen if it's still an issue, but post the command you used to create the container or screenshots if it's a gui method
