### ISSUE TITLE
Add Definition file

### ISSUE THREAD

**Issue by pedrolti0** [linuxserver/docker-cardigann#6]
Hello guys,

I've just ask to cardigan's github, if they can create a new definition (.yml)
Issue : https://github.com/cardigann/cardigann/issues/403
They've created it. But it's for legacy install not for docker.
yml file : https://github.com/cardigann/cardigann/pull/408/commits/22ef68a32ae8396fbe95c6409ad2d7e5840939f2

So i'm coming to you to know how can I add it for docker version.
I've tried to add the file on ./docker/Users/Cardigann/config/definitions/
But when i restart the dock, the new entry doesn't appear.

I've tried to add manually an entry in config.json, but without result.

So, how can add a new definition on this docker version ?

I'm available if you need other information.
Thanks in advance.

**Comment by sparklyballs** [comment]
![screen shot 2017-11-16 at 01 52 25](https://user-images.githubusercontent.com/4343808/32869814-de418928-ca70-11e7-9d98-ef54f2fab442.png)

putting this [file](https://raw.githubusercontent.com/mirwan/cardigann/848efe619ebf27ad60d0a740b1720912e9efbe11/definitions/yggtorrent.yml)  in /config/definitions works as expected

**Comment by pedrolti0** [comment]
Woow, first thanks for you're very fast answer !!

as Viewing your comment i"ve done the same action.
And now it's working.

I don't know how or why. But the mistake can be only on my side.

Thanks again for your return.
